package dev.staj.scavengr.model.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.net.URI;
import java.util.UUID;
import javax.annotation.PostConstruct;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.server.EntityLinks;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Component;



/**
 * Clue Entity has four indexes clue_name, hunt_id, hunt_order, media_tag.
 */
@SuppressWarnings("JpaDataSourceORMInspection")
@Entity
@Component
@Table(
    // TODO we need a way to make sure that each hunt has unique hunt order values,
    //  but still let multiple "Clue 1"s, etc. exist in different hunts.
    uniqueConstraints =
    @UniqueConstraint(columnNames = {"hunt_id", "hunt_order"}),
    indexes = {
        @Index(columnList = "clue_name"),
        @Index(columnList = "media_tag")
    }
)
public class Clue {

  /**
   * EntityLinks is a method which turns the links into Strings and generate a new Link.
   */
  private static EntityLinks entityLinks;

  /**
   *  Id is a unique identifier key so it is generated by uuid2.
   *
   */
  @NonNull
  @Id
  @GeneratedValue(generator = "uuid2")
  @GenericGenerator(name = "uuid2", strategy = "uuid2")
  @Column(name = "clue_id", columnDefinition = "CHAR(16) FOR BIT DATA", nullable = false, updatable = false)
  private UUID id;

  /**
   * clue Name is type String and its not nullable
   * clue name will be set by the organizer and visible to hunters
   */
  @NonNull
  @Column(name = "clue_name", nullable = false)
  private String clueName;

  /**
   * hunt is a foreign key so it has a many to one relationship, one hunt can have many clues.
   */
  @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
  @ManyToOne(fetch = FetchType.LAZY,
      cascade = {CascadeType.DETACH, CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
  @JoinColumn(name = "hunt_id")
  private Hunt hunt;

  /**
   * media is an index in our clue entity which may contain Videos,Articles,Images.
   */
  @NonNull
  @Column(nullable = false)
  private String media;

  /**
   * media tag is an index in clue entity it can be either a QRCode or NFC tag.
   */
  @NonNull
  @Column(name = "media_tag", nullable = false)
  private String mediaTag;

  /**
   * this is an index in clue entity that specify the hunt order.
   */
  @NonNull
  @Column(name = "hunt_order", nullable = false)
  private Integer huntOrder;

  /**
   *
   * @return getHunt gets the Hunts Object.
   */
  public Hunt getHunt() {
    return hunt;
  }

  /**
   * Returns the clue name for this instance.
   */
  @NonNull
  public String getClueName() {
    return clueName;
  }

  /**
   * Sets the clue name for this instance.
   */
  public void setClueName(@NonNull String clueName) {
    this.clueName = clueName;
  }

  /**
   *
   * @return getId returns clue id.
   */
  @NonNull
  public UUID getId() {
    return id;
  }

  /**
   *
   * @return getMedia returns media to user when scanned the QRCode || NFC tags.
   */
  @NonNull
  public String getMedia() {
    return media;
  }

  /**
   *
   * @param media Set the media for any clue in the entity.
   */
  public void setMedia(@NonNull String media) {
    this.media = media;
  }

  /**
   *
   * @return getMediaTag returns the appropriate NFC tag and or QRCode.
   */
  @NonNull
  public String getMediaTag() {
    return mediaTag;
  }

  /**
   *
   * @param mediaTag set MediaTag to appropriate Clue.
   */
  public void setMediaTag(@NonNull String mediaTag) {
    this.mediaTag = mediaTag;
  }

  /**
   *
   * @return hunt order.
   */
  @NonNull
  public Integer getHuntOrder() {
    return huntOrder;
  }

  /**
   *
   * @param huntOrder sets hunts in given order.
   */
  public void setHuntOrder(Integer huntOrder) {
    this.huntOrder = huntOrder;
  }

  /**
   *
   * @param hunt setHunt sets hunt for the User.
   */
  public void setHunt(Hunt hunt) {
    this.hunt = hunt;
  }

  /**
   *
   * @return getHref returns the Link to the CLue.
   */
  public URI getHref() {
    return entityLinks.linkForItemResource(Clue.class, id).toUri();
  }

  /**
   * Converts entity links to string value.
   */
  @PostConstruct
  private void init() {
    entityLinks.toString();
  }

  /**
   *
   * @param entityLinks Generate an entity links value.
   */
  @Autowired
  private void setEntityLinks(EntityLinks entityLinks) {
    Clue.entityLinks = entityLinks;
  }
}
